// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation struct {
	Id        int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nonce     uint64               `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PubKey    []byte               `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature []byte               `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Operation:
	//	*Operation_Heartbeat
	//	*Operation_WithdrawSignature
	Operation            isOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Operation) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Operation) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Operation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Operation) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type Operation_WithdrawSignature struct {
	WithdrawSignature *WithdrawSignature `protobuf:"bytes,11,opt,name=withdrawSignature,proto3,oneof"`
}

func (*Operation_Heartbeat) isOperation_Operation() {}

func (*Operation_WithdrawSignature) isOperation_Operation() {}

func (m *Operation) GetOperation() isOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *Operation) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetOperation().(*Operation_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *Operation) GetWithdrawSignature() *WithdrawSignature {
	if x, ok := m.GetOperation().(*Operation_WithdrawSignature); ok {
		return x.WithdrawSignature
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Operation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Operation_Heartbeat)(nil),
		(*Operation_WithdrawSignature)(nil),
	}
}

type Heartbeat struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type WithdrawSignature struct {
	WithdrawId           int32    `protobuf:"varint,1,opt,name=withdrawId,proto3" json:"withdrawId,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawSignature) Reset()         { *m = WithdrawSignature{} }
func (m *WithdrawSignature) String() string { return proto.CompactTextString(m) }
func (*WithdrawSignature) ProtoMessage()    {}
func (*WithdrawSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *WithdrawSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawSignature.Unmarshal(m, b)
}
func (m *WithdrawSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawSignature.Marshal(b, m, deterministic)
}
func (m *WithdrawSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawSignature.Merge(m, src)
}
func (m *WithdrawSignature) XXX_Size() int {
	return xxx_messageInfo_WithdrawSignature.Size(m)
}
func (m *WithdrawSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawSignature.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawSignature proto.InternalMessageInfo

func (m *WithdrawSignature) GetWithdrawId() int32 {
	if m != nil {
		return m.WithdrawId
	}
	return 0
}

func (m *WithdrawSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Withdraw struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId              int32                `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Recipient            string               `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount               uint64               `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               string               `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PaymentRaw           []byte               `protobuf:"bytes,6,opt,name=paymentRaw,proto3" json:"paymentRaw,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ApplyHash            []byte               `protobuf:"bytes,8,opt,name=applyHash,proto3" json:"applyHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Withdraw) Reset()         { *m = Withdraw{} }
func (m *Withdraw) String() string { return proto.CompactTextString(m) }
func (*Withdraw) ProtoMessage()    {}
func (*Withdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Withdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdraw.Unmarshal(m, b)
}
func (m *Withdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdraw.Marshal(b, m, deterministic)
}
func (m *Withdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdraw.Merge(m, src)
}
func (m *Withdraw) XXX_Size() int {
	return xxx_messageInfo_Withdraw.Size(m)
}
func (m *Withdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdraw.DiscardUnknown(m)
}

var xxx_messageInfo_Withdraw proto.InternalMessageInfo

func (m *Withdraw) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Withdraw) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Withdraw) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Withdraw) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Withdraw) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Withdraw) GetPaymentRaw() []byte {
	if m != nil {
		return m.PaymentRaw
	}
	return nil
}

func (m *Withdraw) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Withdraw) GetApplyHash() []byte {
	if m != nil {
		return m.ApplyHash
	}
	return nil
}

type Withdraws struct {
	Data                 []*Withdraw `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Withdraws) Reset()         { *m = Withdraws{} }
func (m *Withdraws) String() string { return proto.CompactTextString(m) }
func (*Withdraws) ProtoMessage()    {}
func (*Withdraws) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Withdraws) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdraws.Unmarshal(m, b)
}
func (m *Withdraws) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdraws.Marshal(b, m, deterministic)
}
func (m *Withdraws) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdraws.Merge(m, src)
}
func (m *Withdraws) XXX_Size() int {
	return xxx_messageInfo_Withdraws.Size(m)
}
func (m *Withdraws) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdraws.DiscardUnknown(m)
}

var xxx_messageInfo_Withdraws proto.InternalMessageInfo

func (m *Withdraws) GetData() []*Withdraw {
	if m != nil {
		return m.Data
	}
	return nil
}

type Group struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RedeemScript         string               `protobuf:"bytes,3,opt,name=redeemScript,proto3" json:"redeemScript,omitempty"`
	Keepers              []int32              `protobuf:"varint,4,rep,packed,name=keepers,proto3" json:"keepers,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Group) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *Group) GetKeepers() []int32 {
	if m != nil {
		return m.Keepers
	}
	return nil
}

func (m *Group) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Groups struct {
	Data                 []*Group `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups) Reset()         { *m = Groups{} }
func (m *Groups) String() string { return proto.CompactTextString(m) }
func (*Groups) ProtoMessage()    {}
func (*Groups) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Groups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups.Unmarshal(m, b)
}
func (m *Groups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups.Marshal(b, m, deterministic)
}
func (m *Groups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups.Merge(m, src)
}
func (m *Groups) XXX_Size() int {
	return xxx_messageInfo_Groups.Size(m)
}
func (m *Groups) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups.DiscardUnknown(m)
}

var xxx_messageInfo_Groups proto.InternalMessageInfo

func (m *Groups) GetData() []*Group {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Operation)(nil), "message.Operation")
	proto.RegisterType((*Heartbeat)(nil), "message.Heartbeat")
	proto.RegisterType((*WithdrawSignature)(nil), "message.WithdrawSignature")
	proto.RegisterType((*Withdraw)(nil), "message.Withdraw")
	proto.RegisterType((*Withdraws)(nil), "message.Withdraws")
	proto.RegisterType((*Group)(nil), "message.Group")
	proto.RegisterType((*Groups)(nil), "message.Groups")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4f, 0x8b, 0xdb, 0x3e,
	0x10, 0x5d, 0x27, 0x71, 0xb2, 0x9a, 0xe4, 0xb7, 0x10, 0xf1, 0xa3, 0x88, 0xa5, 0xb4, 0xc6, 0xb0,
	0x90, 0x43, 0xf1, 0x42, 0x7a, 0xe9, 0xb5, 0xbd, 0x34, 0xdb, 0x1e, 0x4a, 0xb5, 0x85, 0x9e, 0x95,
	0x78, 0xea, 0x98, 0xc6, 0x96, 0x90, 0x64, 0x42, 0x3e, 0x52, 0x2f, 0xfd, 0x80, 0x3d, 0x15, 0xc9,
	0x96, 0x93, 0x6c, 0x0a, 0xa5, 0xc7, 0xf7, 0x34, 0x33, 0x7a, 0x7f, 0xe0, 0xbf, 0x0a, 0x8d, 0x11,
	0x05, 0x66, 0x4a, 0x4b, 0x2b, 0xe9, 0xa4, 0x83, 0xb7, 0x2f, 0x0b, 0x29, 0x8b, 0x1d, 0xde, 0x7b,
	0x7a, 0xdd, 0x7c, 0xbb, 0xb7, 0x65, 0x85, 0xc6, 0x8a, 0x4a, 0xb5, 0x93, 0xe9, 0xcf, 0x01, 0x90,
	0x4f, 0x0a, 0xb5, 0xb0, 0xa5, 0xac, 0xe9, 0x0d, 0x0c, 0xca, 0x9c, 0x45, 0x49, 0xb4, 0x88, 0xf9,
	0xa0, 0xcc, 0xe9, 0xff, 0x10, 0xd7, 0xb2, 0xde, 0x20, 0x1b, 0x24, 0xd1, 0x62, 0xc4, 0x5b, 0x40,
	0x9f, 0xc1, 0x58, 0x35, 0xeb, 0x8f, 0x78, 0x60, 0xc3, 0x24, 0x5a, 0xcc, 0x78, 0x87, 0xe8, 0x73,
	0x20, 0xa6, 0x2c, 0x6a, 0x61, 0x1b, 0x8d, 0x6c, 0xe4, 0x9f, 0x8e, 0x04, 0x7d, 0x03, 0xa4, 0xff,
	0x9c, 0x91, 0x24, 0x5a, 0x4c, 0x97, 0xb7, 0x59, 0x2b, 0x2f, 0x0b, 0xf2, 0xb2, 0x2f, 0x61, 0x82,
	0x1f, 0x87, 0xe9, 0x12, 0xc8, 0x16, 0x85, 0xb6, 0x6b, 0x14, 0x96, 0x81, 0xdf, 0xa4, 0x59, 0x30,
	0xbc, 0x0a, 0x2f, 0xab, 0x2b, 0x7e, 0x1c, 0xa3, 0x1f, 0x60, 0xbe, 0x2f, 0xed, 0x36, 0xd7, 0x62,
	0xff, 0xd8, 0x6b, 0x9a, 0x76, 0xbf, 0x86, 0xdd, 0xaf, 0x4f, 0x27, 0x56, 0x57, 0xfc, 0x72, 0xed,
	0xdd, 0x14, 0x88, 0x0c, 0x11, 0xa5, 0x77, 0x40, 0xfa, 0x2f, 0x29, 0x83, 0x89, 0x12, 0x87, 0x9d,
	0x14, 0x6d, 0x68, 0x33, 0x1e, 0x60, 0xfa, 0x19, 0xe6, 0x17, 0xd7, 0xe9, 0x0b, 0x80, 0x70, 0xfd,
	0x21, 0xc4, 0x7c, 0xc2, 0x9c, 0x07, 0x38, 0x78, 0x12, 0x60, 0xfa, 0x2b, 0x82, 0xeb, 0x70, 0xf3,
	0xa2, 0x29, 0x06, 0x93, 0x42, 0xcb, 0x46, 0x3d, 0xe4, 0x7e, 0x31, 0xe6, 0x01, 0xba, 0xa3, 0x1a,
	0x37, 0xa5, 0x2a, 0xb1, 0xb6, 0xbe, 0x30, 0xc2, 0x8f, 0x84, 0xeb, 0x52, 0x54, 0xb2, 0xa9, 0xad,
	0x2f, 0x6c, 0xc4, 0x3b, 0xe4, 0x78, 0x63, 0x85, 0x6d, 0x0c, 0x8b, 0xfd, 0x4a, 0x87, 0x9c, 0x05,
	0x25, 0x0e, 0x15, 0xd6, 0x96, 0x8b, 0x3d, 0x1b, 0x7b, 0x8d, 0x27, 0x8c, 0x6b, 0x79, 0xa3, 0x51,
	0x58, 0xcc, 0xdf, 0x5a, 0x36, 0xf9, 0x7b, 0xcb, 0xfd, 0xb0, 0xd3, 0x29, 0x94, 0xda, 0x1d, 0x56,
	0xc2, 0x6c, 0xd9, 0x75, 0x6b, 0xbe, 0x27, 0xd2, 0x25, 0x90, 0xe0, 0xdd, 0xd0, 0x3b, 0x18, 0xe5,
	0xc2, 0x0a, 0x16, 0x25, 0xc3, 0xc5, 0x74, 0x39, 0xbf, 0xe8, 0x93, 0xfb, 0xe7, 0xf4, 0x47, 0x04,
	0xf1, 0x7b, 0x97, 0xc2, 0x9f, 0xd2, 0x12, 0x79, 0xae, 0xd1, 0x18, 0x9f, 0x16, 0xe1, 0x01, 0xd2,
	0x14, 0x66, 0x1a, 0x73, 0xc4, 0xea, 0x71, 0xa3, 0x4b, 0x15, 0x02, 0x3b, 0xe3, 0xdc, 0xf6, 0x77,
	0x44, 0x85, 0xda, 0xb0, 0x51, 0x32, 0x74, 0x59, 0x77, 0xf0, 0xdc, 0x7d, 0xfc, 0x0f, 0xee, 0xd3,
	0x57, 0x30, 0xf6, 0x52, 0x9d, 0x82, 0x53, 0x73, 0x37, 0xbd, 0x39, 0xff, 0xdc, 0x3a, 0x5b, 0x8f,
	0xfd, 0xb1, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x29, 0x51, 0xad, 0x51, 0xf7, 0x03, 0x00,
	0x00,
}
