// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation struct {
	Id        int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nonce     uint64               `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PubKey    []byte               `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature []byte               `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Operation:
	//	*Operation_Heartbeat
	Operation            isOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Operation) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Operation) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Operation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Operation) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

func (*Operation_Heartbeat) isOperation_Operation() {}

func (m *Operation) GetOperation() isOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *Operation) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetOperation().(*Operation_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Operation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Operation_Heartbeat)(nil),
	}
}

type Heartbeat struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Operation)(nil), "message.Operation")
	proto.RegisterType((*Heartbeat)(nil), "message.Heartbeat")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xdd, 0xd8, 0x3f, 0xec, 0xb4, 0x7a, 0x18, 0x44, 0x96, 0x22, 0x18, 0x0a, 0x42, 0x4e,
	0x5b, 0xa8, 0x17, 0xcf, 0x9e, 0x0a, 0x1e, 0x84, 0xc5, 0x17, 0x98, 0xd8, 0x31, 0x2e, 0x34, 0x99,
	0x25, 0xd9, 0x1c, 0xfa, 0xba, 0x3e, 0x89, 0x90, 0x74, 0x9b, 0xe3, 0x6f, 0xbe, 0xdf, 0xb2, 0xdf,
	0x07, 0x77, 0x35, 0x77, 0x1d, 0x55, 0x6c, 0x43, 0x2b, 0x51, 0x70, 0x79, 0xc1, 0xcd, 0x73, 0x25,
	0x52, 0x9d, 0x78, 0x37, 0x9c, 0xcb, 0xfe, 0x67, 0x17, 0x7d, 0xcd, 0x5d, 0xa4, 0x3a, 0x8c, 0xe6,
	0xf6, 0x4f, 0x81, 0xfe, 0x0c, 0xdc, 0x52, 0xf4, 0xd2, 0xe0, 0x3d, 0x64, 0xfe, 0x68, 0x54, 0xae,
	0x8a, 0xb9, 0xcb, 0xfc, 0x11, 0x1f, 0x60, 0xde, 0x48, 0xf3, 0xcd, 0x26, 0xcb, 0x55, 0x31, 0x73,
	0x23, 0xe0, 0x23, 0x2c, 0x42, 0x5f, 0x7e, 0xf0, 0xd9, 0xdc, 0xe6, 0xaa, 0x58, 0xbb, 0x0b, 0xe1,
	0x13, 0xe8, 0xce, 0x57, 0x0d, 0xc5, 0xbe, 0x65, 0x33, 0x1b, 0xa2, 0xe9, 0x80, 0x6f, 0xa0, 0xaf,
	0x9f, 0x1b, 0x9d, 0xab, 0x62, 0xb5, 0xdf, 0xd8, 0xb1, 0x9e, 0x4d, 0xf5, 0xec, 0x57, 0x32, 0xdc,
	0x24, 0xe3, 0x1e, 0xf4, 0x2f, 0x53, 0x1b, 0x4b, 0xa6, 0x68, 0x60, 0x78, 0x89, 0x36, 0x0d, 0x3e,
	0xa4, 0xe4, 0x70, 0xe3, 0x26, 0xed, 0x7d, 0x05, 0x5a, 0xd2, 0xac, 0xed, 0x0b, 0xe8, 0xab, 0x86,
	0x06, 0x96, 0x81, 0xce, 0x27, 0xa1, 0x71, 0xe8, 0xda, 0x25, 0x2c, 0x17, 0x43, 0x8d, 0xd7, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x15, 0xa9, 0x66, 0x4d, 0x01, 0x00, 0x00,
}
